# -*- coding: utf-8 -*-
"""Birdsong Data AI Notebook 2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IYl0Myy5MEmnGYFAi1ai4l7K-b-vezzE

# Saving a Copy and Renaming Your Notebook

To save a copy of this notebook with your first and last name added to the front of the title, follow these steps:

- **Step 1:** Go to the **File** menu at the top of the notebook.
- **Step 2:** Click on **"Save a copy in Drive"** to create a copy of the notebook in your Google Drive.
- **Step 3:** Once the copy is saved, click on the notebook title at the top of the page.
- **Step 4:** In the rename dialog that appears, prepend your first and last name to the existing notebook name (e.g., "JohnDoe_Birdsong_Classification.ipynb").
- **Step 5:** Click **"OK"** to confirm the new name.

Now, your notebook is saved with your name included in the title

# Introduction to Birdsong Classification and Audio Data Processing

Welcome to the Birdsong Classification project. In this notebook, you'll learn how to process and analyze audio data—specifically, bird vocalizations—to extract meaningful patterns and features. This kind of data processing is a critical tool in the study of animal behavior and bioacoustics. Below is a brief overview of what this project is about and why it is important.

## What This Project Covers

- **Audio Processing and Visualization:**  
  You will work with raw audio files (both WAV and .m4a formats). The project guides you through downloading, loading, and visualizing these audio samples by plotting their waveforms and spectrograms. These visualizations help you see how the sound changes over time and across different frequencies.

- **Feature Extraction:**  
  The notebook demonstrates how to extract key features from the audio data, such as MFCCs (Mel Frequency Cepstral Coefficients). MFCCs are widely used in audio signal processing because they capture the timbral (quality) aspects of sound that are important for distinguishing between different bird species.

- **Machine Learning with Autoencoders:**  
  You will learn to train an autoencoder—a type of neural network that compresses data into a lower-dimensional space. By reducing the complex MFCC feature data to a 2-dimensional embedding, the project shows how similar bird sounds can be clustered together based on their features. This clustering can help identify patterns in bird vocalizations that may relate to behavior or species differences.

- **Data Organization and Archiving:**  
  The project also covers how to handle large datasets by organizing audio files into directories (e.g., one directory per bird species) and processing them in batch mode. This is especially useful in real-world studies where researchers work with extensive audio archives from field recordings.

## Why This is Important in the Study of Animal Behaviors

Understanding and analyzing animal sounds, such as birdsong, is essential for several reasons:

- **Species Identification and Monitoring:**  
  By classifying bird songs, researchers can monitor populations, track migration patterns, and even detect the presence of endangered species. Automated audio analysis helps to efficiently process large volumes of data collected in the field.

- **Behavioral Insights:**  
  Birdsong carries information about communication, mating, territorial behavior, and even environmental changes. Analyzing these vocalizations can reveal insights into how birds interact with each other and their surroundings.

- **Conservation Efforts:**  
  Effective monitoring and understanding of bird vocalizations contribute to conservation efforts. By detecting changes in bird behavior or population dynamics through audio analysis, scientists and conservationists can take timely action to protect vulnerable species.

- **Advancing Bioacoustics Research:**  
  This project introduces you to techniques that are at the forefront of bioacoustics research. Learning how to process, analyze, and cluster audio data is not only valuable for ornithology but also for the broader field of animal behavior studies.

## What to Expect

Throughout this notebook, you'll find detailed explanations, comments, and guided code blocks. Each section builds on the previous ones, starting with basic audio visualization and moving towards advanced machine learning techniques. By the end of the project, you will have a better understanding of how to handle and analyze audio data, and you'll appreciate the role such analyses play in studying and conserving wildlife.

# Getting Started with Running Cells in Google Colab

**Running a Cell:**
- To run a cell, simply click the small "Play" button on the left side of the cell.
- Alternatively, press **Shift + Enter** on your keyboard to run the cell and automatically move to the next one.

**Adding New Cells:**
- Click the **"+ Code"** button at the top of the notebook to add a new code cell.
- Click the **"+ Text"** button to add a new text (Markdown) cell.

That's it! Running cells is the basic way to execute your code and see the output in Google Colab.
"""

2+2

2**8

2**12345

"""# Cell 1: Install Dependencies and Import Libraries

In this section, we install the necessary packages (such as `pydub`) and import all the libraries we need for our project. This includes libraries for audio processing (like `librosa` and `pydub`), plotting (`matplotlib`), numerical computations (`numpy`), machine learning (`torch`), and more. This cell sets up our working environment.
"""

!pip install pydub

import os               # For file system operations
import glob             # For matching file patterns
import numpy as np      # For numerical operations
import matplotlib.pyplot as plt  # For plotting

import librosa          # For audio processing
import librosa.display  # For visualizing audio data

import requests         # For downloading files from URLs
from IPython.display import Audio, display  # For playing audio in the notebook

from pydub import AudioSegment  # For handling .m4a files

# For Google Colab – mount Google Drive if needed
try:
    from google.colab import drive
except ImportError:
    drive = None

import torch            # For tensor operations and machine learning
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import LabelEncoder, StandardScaler

"""# Cell 2: Define Utility Functions

This section defines several helper functions that will be used throughout the notebook. The functions include:
- **`plot_waveform`**: Displays the audio waveform.
- **`plot_spectrogram`**: Displays the spectrogram of the audio.
- **`download_audio`**: Downloads an audio file from a given URL.

These functions simplify our code by handling repetitive tasks.
"""

def plot_waveform(y, sr, title="Waveform"):
    """Plot the waveform of an audio signal."""
    plt.figure(figsize=(10, 3))
    librosa.display.waveshow(y, sr=sr)
    plt.title(title)
    plt.xlabel("Time (s)")
    plt.ylabel("Amplitude")
    plt.show()




def plot_spectrogram(y, sr, title="Spectrogram"):
    """Plot the spectrogram of an audio signal."""
    D = np.abs(librosa.stft(y))
    S_db = librosa.amplitude_to_db(D, ref=np.max)
    plt.figure(figsize=(10, 4))
    librosa.display.specshow(S_db, sr=sr, x_axis='time', y_axis='log')
    plt.colorbar(format='%+2.0f dB')
    plt.title(title)
    plt.show()


def download_audio(url, file_name):
    """Download an audio file from a URL and save it locally."""
    print(f"Downloading {file_name}...")
    response = requests.get(url)
    with open(file_name, 'wb') as f:
        f.write(response.content)
    print(f"{file_name} downloaded successfully.\n")

"""# Section 1: Process Original Bird Data (WAV Files)

In this section, we download a few sample bird audio files (in WAV format) from the web. We then load these files using `librosa`, display their waveforms and spectrograms, and even play the audio directly in the notebook. This section introduces basic audio processing and visualization techniques.
"""

def process_wav_samples():
    print("\n=== Processing Original Bird Data Samples ===\n")

    audio_samples = [
        {
            'url': 'https://soundcamp.org/sounds/382/birdsong_in_woodland_DGc.wav',
            'file_name': 'birdsong_in_woodland.wav'
        },
        {
            'url': 'https://soundcamp.org/sounds/383/canary_trill_yellow_2w6__oGr.wav',
            'file_name': 'canary.wav'
        },
        {
            'url': 'https://soundcamp.org/sounds/380/blackbird_song_5_g6O.wav',
            'file_name': 'blackbird.wav'
        }
    ]

    for sample in audio_samples:
        try:
            download_audio(sample['url'], sample['file_name'])
            y, sr = librosa.load(sample['file_name'], sr=None)
            print(f"Loaded {sample['file_name']} (sr={sr}, duration={len(y)/sr:.2f}s)")
            plot_waveform(y, sr, title=f"Waveform of {sample['file_name']}")
            plot_spectrogram(y, sr, title=f"Spectrogram of {sample['file_name']}")
            print(f"Playing {sample['file_name']}...")
            display(Audio(y, rate=sr))
        except Exception as e:
            print(f"Error processing {sample['file_name']}: {e}")

process_wav_samples()            # Process WAV samples

"""# Section 2: Process Birdsong Archive (Organized by Species)

Here, we process a birdsong archive stored on Google Drive. The archive is organized into subfolders—each subfolder corresponds to a different bird species and contains WAV files. In this section, we:
- Mount Google Drive (if using Colab).
- Load the audio files and assign labels based on their species.
- Save the processed audio data as tensors.
- Visualize a montage of spectrograms for each species.

This part demonstrates handling larger datasets and file organization.
"""

def process_birdsong_archive():
    print("\n=== Processing Birdsong Archive ===\n")

    if drive is not None:
        print("Mounting Google Drive for archive processing...")
        drive.mount('/content/drive', force_remount=False)

    files_directory = "/content/drive/MyDrive/birdsong_archive/Rindy's bird songs/"

    data_list = []
    label_list = []

    folders = os.listdir(files_directory)

    label_encoder = LabelEncoder()
    label_encoder.fit(folders)

    def load_file(file_path, duration=10):
        try:
            audio_data, _ = librosa.load(file_path, sr=None, duration=duration)
            return torch.tensor(audio_data)
        except Exception as e:
            print(f"Error loading {file_path}: {e}")
            return None

    for folder in folders:
        folder_path = os.path.join(files_directory, folder)
        if os.path.isdir(folder_path):
            label = label_encoder.transform([folder])[0]
            for file_name in os.listdir(folder_path):
                file_path = os.path.join(folder_path, file_name)
                if file_name.endswith('.wav'):
                    print(f"Processing: {file_path}")
                    file_data = load_file(file_path)
                    if file_data is not None:
                        data_list.append(file_data)
                        label_list.append(label)
                    else:
                        print(f"Skipping file: {file_path}")
                else:
                    print(f"Skipped non-wav file: {file_name}")

    if data_list:
        data_tensor = torch.nn.utils.rnn.pad_sequence(data_list, batch_first=True)
        label_tensor = torch.tensor(label_list)
        torch.save(data_tensor, "/content/drive/MyDrive/birdsong_archive/birdsong_data_tensor.pt")
        torch.save(label_tensor, "/content/drive/MyDrive/birdsong_archive/birdsong_labels_tensor.pt")
        print("Tensors saved successfully.")
    else:
        print("No data was processed in the archive.")
        return

    data_tensor = torch.load("/content/drive/MyDrive/birdsong_archive/birdsong_data_tensor.pt")
    label_tensor = torch.load("/content/drive/MyDrive/birdsong_archive/birdsong_labels_tensor.pt")

    folders = os.listdir(files_directory)
    label_encoder = LabelEncoder()
    label_encoder.fit(folders)
    label_decoder = dict(zip(label_encoder.transform(folders), folders))

    def create_spectrogram_from_tensor(audio_tensor, sr, ax, label):
        audio_data = audio_tensor.numpy()
        S = librosa.feature.melspectrogram(y=audio_data, sr=sr, n_mels=128, fmax=8000)
        S_db = librosa.power_to_db(S, ref=np.max)
        librosa.display.specshow(S_db, sr=sr, ax=ax, x_axis='time', y_axis='mel')
        ax.set_title(label, fontsize=10)
        ax.set_xticks([])
        ax.set_yticks([])

    num_samples = 8
    unique_labels = torch.unique(label_tensor).tolist()
    sample_rate = 22050

    for encoded_label in unique_labels:
        indices = (label_tensor == encoded_label).nonzero(as_tuple=True)[0]
        bird_name = label_decoder[encoded_label]
        num_plots = min(len(indices), num_samples)

        fig, axs = plt.subplots(1, num_plots, figsize=(15, 3))
        fig.suptitle(f"Spectrograms for {bird_name}", fontsize=16)

        for j in range(num_plots):
            idx = indices[j].item()
            audio_tensor = data_tensor[idx]
            ax = axs[j] if num_plots > 1 else axs
            create_spectrogram_from_tensor(audio_tensor, sample_rate, ax, bird_name)

        plt.tight_layout()
        plt.show()

process_birdsong_archive()              # Process the birdsong archive from Google Drive

"""# Section 3: Embedding Clustering on Archive MFCC Features

In this section, we extract MFCC (Mel Frequency Cepstral Coefficients) features from the archive data and train an autoencoder to compress these features into a 2D space. We then visualize the resulting 2D embeddings, with each point labeled by the bird species. This introduces feature extraction and unsupervised learning techniques.
"""

def process_embedding_clustering():
    print("\n=== Embedding Clustering on Birdsong Archive MFCC Features ===\n")

    data_tensor = torch.load("/content/drive/MyDrive/birdsong_archive/birdsong_data_tensor.pt")
    label_tensor = torch.load("/content/drive/MyDrive/birdsong_archive/birdsong_labels_tensor.pt")

    files_directory = "/content/drive/MyDrive/birdsong_archive/Rindy's bird songs/"
    folders = os.listdir(files_directory)
    label_encoder = LabelEncoder()
    label_encoder.fit(folders)
    label_decoder = dict(zip(label_encoder.transform(folders), folders))

    sample_rate = 22050
    n_mfcc = 13

    feature_list = []
    label_list = []

    for i in range(len(data_tensor)):
        audio_tensor = data_tensor[i]
        audio_data = audio_tensor.numpy()
        mfcc = librosa.feature.mfcc(y=audio_data, sr=sample_rate, n_mfcc=n_mfcc)
        mfcc_mean = np.mean(mfcc, axis=1)
        mfcc_std = np.std(mfcc, axis=1)
        feature_vector = np.concatenate((mfcc_mean, mfcc_std))
        feature_list.append(feature_vector)
        label_list.append(label_tensor[i].item())

    X = np.array(feature_list)
    y = np.array(label_list)

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    X_tensor = torch.tensor(X_scaled, dtype=torch.float32)

    class Autoencoder(nn.Module):
        def __init__(self, input_dim):
            super(Autoencoder, self).__init__()
            self.encoder = nn.Sequential(
                nn.Linear(input_dim, 128),
                nn.ReLU(),
                nn.Linear(128, 64),
                nn.ReLU(),
                nn.Linear(64, 2)
            )
            self.decoder = nn.Sequential(
                nn.Linear(2, 64),
                nn.ReLU(),
                nn.Linear(64, 128),
                nn.ReLU(),
                nn.Linear(128, input_dim)
            )
        def forward(self, x):
            encoded = self.encoder(x)
            decoded = self.decoder(encoded)
            return encoded, decoded

    input_dim = X_scaled.shape[1]
    autoencoder = Autoencoder(input_dim)
    criterion = nn.MSELoss()
    optimizer = optim.Adam(autoencoder.parameters(), lr=0.0001)

    num_epochs = 5000
    autoencoder.train()
    for epoch in range(num_epochs):
        optimizer.zero_grad()
        encoded, decoded = autoencoder(X_tensor)
        loss = criterion(decoded, X_tensor)
        loss.backward()
        optimizer.step()
        if (epoch + 1) % 500 == 0:
            print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")

    autoencoder.eval()
    with torch.no_grad():
        embeddings, _ = autoencoder(X_tensor)
    embeddings = embeddings.cpu().numpy()

    plt.figure(figsize=(12, 8))
    unique_labels = np.unique(y)
    for label in unique_labels:
        idx = y == label
        plt.scatter(embeddings[idx, 0], embeddings[idx, 1],
                    label=label_decoder[label], alpha=0.7)
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize='small')
    plt.title('2D Embedding Learned by Autoencoder (Bird Song MFCC Features)')
    plt.xlabel('Component 1')
    plt.ylabel('Component 2')
    plt.grid(True)
    plt.tight_layout()
    plt.show()

process_embedding_clustering()          # Run embedding clustering on the archive MFCC features

"""# Section 4: Process .m4a Files from Google Drive

This section focuses on processing .m4a audio files. We use `pydub` to load and convert the files, then:
- Normalize the audio samples.
- Display the waveform and spectrogram.
- Play the audio within the notebook.

This step is important for learning how to handle different audio file formats.
"""

def load_m4a_file(file_path):
    """
    Load an m4a audio file using pydub, convert samples to float, and normalize them.
    Returns:
        samples: A float32 numpy array scaled to [-1, 1].
        sr: Sampling rate.
    """
    audio = AudioSegment.from_file(file_path, format='m4a')
    samples = np.array(audio.get_array_of_samples())
    if audio.channels == 2:
        samples = samples.reshape((-1, 2)).mean(axis=1)
    samples = samples.astype(np.float32)
    max_val = float(2 ** (8 * audio.sample_width - 1))
    samples /= max_val
    sr = audio.frame_rate
    return samples, sr


def process_m4a_files():
    print("\n=== Processing .m4a Files from Google Drive ===\n")

    if drive is not None:
        print("Mounting Google Drive...")
        drive.mount('/content/drive', force_remount=False)
    else:
        print("Google Drive not available. Ensure you are running in Colab.")

    audio_folder = '/content/drive/MyDrive/Audio'
    pattern = os.path.join(audio_folder, '*.m4a')
    audio_files = glob.glob(pattern)

    print(f"Found {len(audio_files)} .m4a files in {audio_folder}")

    for file in audio_files:
        print(f"\nProcessing file: {file}")
        try:
            y, sr = load_m4a_file(file)
            print(f"Loaded {os.path.basename(file)} (sr={sr}, duration={len(y)/sr:.2f}s)")
            plot_waveform(y, sr, title=f"Waveform of {os.path.basename(file)}")
            plot_spectrogram(y, sr, title=f"Spectrogram of {os.path.basename(file)}")
            print(f"Playing {os.path.basename(file)}...")
            display(Audio(y, rate=sr))
        except Exception as e:
            print(f"Error processing {file}: {e}")

"""# Section 5: Embedding Clustering on .m4a Files (Grouped by 5 Files per Class)

In the final processing section, we extract MFCC features from the .m4a files. We assume that every 5 files belong to one class (e.g., Class A, Class B, etc.). Then we:
- Train an autoencoder to reduce the features to a 2D embedding.
- Visualize the 2D embeddings to observe clustering based on these groupings.

This section demonstrates clustering techniques on features extracted from audio data.
"""

def process_m4a_embedding_clustering():
    print("\n=== Embedding Clustering on .m4a Files Features ===\n")

    if drive is not None:
        print("Mounting Google Drive...")
        drive.mount('/content/drive', force_remount=False)

    m4a_folder = '/content/drive/MyDrive/Audio'
    pattern = os.path.join(m4a_folder, '*.m4a')
    audio_files = sorted(glob.glob(pattern))
    print(f"Found {len(audio_files)} .m4a files in {m4a_folder}")

    feature_list = []
    label_list = []
    group_size = 5

    for i, file in enumerate(audio_files):
        try:
            y, sr = load_m4a_file(file)
            mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)
            mfcc_mean = np.mean(mfcc, axis=1)
            mfcc_std = np.std(mfcc, axis=1)
            feature_vector = np.concatenate((mfcc_mean, mfcc_std))
            feature_list.append(feature_vector)
            group_index = i // group_size
            class_label = chr(ord('A') + group_index)
            label_list.append(class_label)
        except Exception as e:
            print(f"Error processing {file}: {e}")

    X = np.array(feature_list)
    y = np.array(label_list)

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    X_tensor = torch.tensor(X_scaled, dtype=torch.float32)

    class Autoencoder(nn.Module):
        def __init__(self, input_dim):
            super(Autoencoder, self).__init__()
            self.encoder = nn.Sequential(
                nn.Linear(input_dim, 128),
                nn.ReLU(),
                nn.Linear(128, 64),
                nn.ReLU(),
                nn.Linear(64, 2)
            )
            self.decoder = nn.Sequential(
                nn.Linear(2, 64),
                nn.ReLU(),
                nn.Linear(64, 128),
                nn.ReLU(),
                nn.Linear(128, input_dim)
            )
        def forward(self, x):
            encoded = self.encoder(x)
            decoded = self.decoder(encoded)
            return encoded, decoded

    input_dim = X_scaled.shape[1]
    autoencoder = Autoencoder(input_dim)
    criterion = nn.MSELoss()
    optimizer = optim.Adam(autoencoder.parameters(), lr=0.0001)

    num_epochs = 2000
    autoencoder.train()
    for epoch in range(num_epochs):
        optimizer.zero_grad()
        encoded, decoded = autoencoder(X_tensor)
        loss = criterion(decoded, X_tensor)
        loss.backward()
        optimizer.step()
        if (epoch + 1) % 200 == 0:
            print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")

    autoencoder.eval()
    with torch.no_grad():
        embeddings, _ = autoencoder(X_tensor)
    embeddings = embeddings.cpu().numpy()

    plt.figure(figsize=(10,8))
    unique_classes = np.unique(y)
    for cl in unique_classes:
        idx = y == cl
        plt.scatter(embeddings[idx, 0], embeddings[idx, 1],
                    label=cl, alpha=0.7)
    plt.legend(title="Class Label")
    plt.title("2D Embeddings for .m4a Files MFCC Features (Grouped by 5 Files per Class)")
    plt.xlabel("Embedding Dimension 1")
    plt.ylabel("Embedding Dimension 2")
    plt.grid(True)
    plt.tight_layout()
    plt.show()

process_m4a_files()                     # Process .m4a files from Google Drive
process_m4a_embedding_clustering()      # Run embedding clustering on the .m4a file features

